# Generated by Django 4.0.3 on 2023-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.IntegerField(default=1)),
                ('domain', models.IntegerField(default=1)),
                ('size', models.IntegerField(default=1024)),
                ('ftp', models.IntegerField(default=1)),
                ('db', models.IntegerField(default=1)),
                ('db_size', models.IntegerField(default=10)),
                ('ssh', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
