# Generated by Django 4.0.3 on 2023-04-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_balancehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
    ]
