# Generated by Django 4.0.3 on 2023-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_balancehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
    ]
